/**
 * Copyright © 2024 Marcelo H Moraes
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the “Software”), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "streamDeco_objects.hpp"

namespace streamDeco
{

    /**
     * @brief  Process event generated by buttons and send keyboard shortcuts com PC
     * @param  button_event  Each button send a different event
     * @param  settings      Reference to settings variables
     * @note   This function is called by button handler on file streamDeco_HandlerButtons.cpp
     */
    void process_event(uint32_t button_event)
    {
        lvgl::screen::rotation_t rotation;

        /** @brief  Each code do diferrent things on this switch case
         *          the keyboard code sended by bleKeyborad is configured herer
         **/
        switch (button_event)
        {

        /**
         * @brief    Nothing happens
         * @details  If nothing happens, do nothing is the better option
         * @note     If nothing happens, do nothing is the better option
         * @param    nothing_event  do nothing
         * @return   nothing
         */
        case nothing_event:
            /* do nothing */
            break;

            /* --- MAIN CANVAS --- */

            /* First row buttons */

            /**
             * @brief    Terminal button is pressed
             * @details  Open a terminal
             * @note     Need configuration on application or system
             **/
        case terminal_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press(KEY_RETURN);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Files button is pressed
         *  @details  Open file manager
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case files_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press('e');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Web button is pressed
         *  @details  Open web browser
         *  @note     This media shortcut may work by default on Windows
         *            On Linux need configuration on system
         **/
        case web_event:
            bleKeyboard.write(KEY_MEDIA_WWW_HOME);
            break;

        /** @brief    Search button is pressed
         *  @details  Open search feature
         *  @note     This media shortcut may work by default on Windows 11 and Linux KDE Plasma
         **/
        case search_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press('s');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Applications button receive a short click
         *  @details  This event will:
         *              Unpin the Applications canvas
         *              Hidden Multimedia and Configurations canvas
         *              Change de hidden state of Applications canvas
         *  @note     The canvas will be hidden automaticaly after time defined on timer uiReset
         *            or with other short click on Applications button
         *            Do nothing if Multimedia or Configurations canvas is pinned
         **/
        case applications_canvas_event:
            if (streamDecoButtons::multimedia_canvas.pinned())
                break;
            if (streamDecoButtons::configurations_canvas.pinned())
                break;
            streamDecoButtons::applications_canvas.unpin();
            streamDecoCanvas::multimedia.hidden();
            streamDecoCanvas::configurations.hidden();
            streamDecoCanvas::monitor.hidden();
            streamDecoCanvas::applications.change_hidden();
            break;

        /** @brief    Applications button receive a long click
         *  @details  This event will:
         *              Fixe and unhidden the Applications canvas
         *              Hidden Multimedia and Configurations canvas
         *            A pinned canvas will not be hidden until a short click on Applications button
         *  @note     Do nothing if Multimedia or Configurations canvas is pinned
         **/
        case applications_canvas_fix_event:
            if (streamDecoButtons::multimedia_canvas.pinned())
                break;
            if (streamDecoButtons::configurations_canvas.pinned())
                break;
            streamDecoButtons::applications_canvas.pin();
            streamDecoCanvas::multimedia.hidden();
            streamDecoCanvas::monitor.hidden();
            streamDecoCanvas::configurations.hidden();
            streamDecoCanvas::applications.unhidden();
            break;

        /* Second row buttons */

        /** @brief    Multimedia_prev button is pressed
         *  @details  Backward media on pcanvas
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case multimedia_prev_event:
            bleKeyboard.write(KEY_MEDIA_PREVIOUS_TRACK);
            break;

        /** @brief    Multimedia_play button is pressed
         *  @details  Play or pause media on player
         *  @note     This media shortcut may work by default on Windows and Linux
         *            This button have two icons, play_simp and pause_simp
         *            SwapIcon method change between this two icons
         *            Also the button is destaqued when pressed,
         *            but have no feedback from computer music player to indentify if media is playing or paused
         */
        case multimedia_play_event:
            bleKeyboard.write(KEY_MEDIA_PLAY_PAUSE);
            streamDecoButtons::multimedia_play.iconSwap();
            if (streamDecoButtons::multimedia_play.pinned())
                streamDecoButtons::multimedia_play.unpin();
            else
                streamDecoButtons::multimedia_play.pin();
            break;

        /** @brief    Multimedia_next button is pressed
         *  @details  Forward media on player
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case multimedia_next_event:
            bleKeyboard.write(KEY_MEDIA_NEXT_TRACK);
            break;

        /** @brief    Multimedia_mic button is pressed
         *  @details  Mute and unmute the microphone
         *  @note     This media shortcut need be configured in application or system
         *            This button have two icons, mic_on_simp and mic_off_simp
         *            SwapIcon method change between this two icons
         *            Also the button is destaqued when pressed,
         *            but have no feedback from computer to indentify the microphone state
         */
        case multimedia_mic_event: /*  */
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press(KEY_F2);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            streamDecoButtons::multimedia_mic.iconSwap();
            if (streamDecoButtons::multimedia_mic.pinned())
                streamDecoButtons::multimedia_mic.unpin();
            else
                streamDecoButtons::multimedia_mic.pin();
            break;

        /** @brief    Multimedia button receive a short click
         *  @details  This event will:
         *              Unpin the Multimedia canvas
         *              Hidden Applications and Configurations canvas
         *              Change de hidden state of Multimedia canvas
         *            The canvas will be hidden automaticaly after time defined on timer uiReset
         *            or with other short click on Multimedia button
         *  @note     Do nothing if Applications or Configurations canvas is pinned
         **/
        case multimedia_canvas_event: /* multimedia button receive a short click */
            if (streamDecoButtons::applications_canvas.pinned())
                break;
            if (streamDecoButtons::configurations_canvas.pinned())
                break;
            streamDecoButtons::multimedia_canvas.unpin();
            streamDecoCanvas::applications.hidden();
            streamDecoCanvas::configurations.hidden();
            streamDecoCanvas::monitor.hidden();
            streamDecoCanvas::multimedia.change_hidden();
            break;

        /** @brief    Multimedia button receive a long click
         *  @details  This event will:
         *              Fixe and unhidden the Multimedia canvas
         *              Hidden Applications and Configurations canvas
         *            A pinned canvas will not be hidden until a short click on Multimedia button
         *  @note     Do nothing if Applications or Configurations canvas is pinned
         **/
        case multimedia_canvas_fix_event:
            if (streamDecoButtons::applications_canvas.pinned())
                break;
            if (streamDecoButtons::configurations_canvas.pinned())
                break;
            streamDecoButtons::multimedia_canvas.pin();
            streamDecoCanvas::applications.hidden();
            streamDecoCanvas::configurations.hidden();
            streamDecoCanvas::monitor.hidden();
            streamDecoCanvas::multimedia.unhidden();
            break;

        /* Third row buttons */

        /** @brief    Prev_workspace button is pressed
         *  @details  Go to left workspace if exsist
         *  @note     This shortcut may work by default on Windows 11
         *            On Linux need configuration on system
         **/
        case left_workspace_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ARROW);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Next_workspace button is pressed
         *  @details  Go to right workspace if exsist
         *  @note     This shortcut may work by default on Windows 11
         *            On Linux need configuration on system
         **/
        case right_workspace_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_RIGHT_ARROW);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Pin_window button is pressed
         *  @details  Pin the active window on canvas
         *  @note     Need configuration on application or system
         *            The button is destaqued when pressed,
         *            but have no feedback from computer to indentify a pinnned window
         **/
        case pin_window_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press('t');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            streamDecoButtons::pin.iconSwap();
            streamDecoButtons::pin.pinned() ? streamDecoButtons::pin.unpin() : streamDecoButtons::pin.pin();
            break;

        /** @brief    Lock_computer button is pressed
         *  @details  Lock the computer
         *  @note     This shortcut may work by default on Windows and Linux
         **/
        case lock_computer_event:
#if 0
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press('l');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
#endif
            break;

        /** @brief    desktop_mode button is pressed
         *  @details  Change desktop mode between multi windows and single window (macos stage manager)
         *  @note     This media shortcut need be configured in application or system
         *            This button have two icons, mult_window_simp and single_window_simp
         *            SwapIcon method change between this two icons
         *            Also this button is destaqued when pressed,
         *            but have no feedback from computer to indentify the desktop state
         */
        case desktop_mode_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_F7);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            streamDecoButtons::desktop_mode.iconSwap();
            streamDecoButtons::desktop_mode.pinned() ? streamDecoButtons::desktop_mode.unpin() : streamDecoButtons::desktop_mode.pin();
            break;

        /** @brief    Configurations button receive a short click
         *  @details  This event will:
         *              Hidden Applications and Multimedia canvas
         *              Change de hidden state of Configurations canvas
         *            The canvas will be hidden automaticaly after time defined on timer uiReset
         *            or with other short click on Configurations button
         *  @note     Do nothing if Applications or Multimedia canvas is pinned
         *            The Configurations canvas have no pin function
         **/
        case configurations_canvas_event: /* configuration button is pressed */
            if (streamDecoButtons::applications_canvas.pinned())
                break;
            if (streamDecoButtons::multimedia_canvas.pinned())
                break;
            streamDecoButtons::configurations_canvas.unpin();
            streamDecoCanvas::applications.hidden();
            streamDecoCanvas::multimedia.hidden();
            if (streamDecoCanvas::monitor.is_hidden())
            {
                streamDecoCanvas::configurations.change_hidden();
            }
            else
            {
                streamDecoCanvas::configurations.hidden();
            }
            streamDecoCanvas::monitor.hidden();
            break;

        /** @brief    Configurations button receive a long click
         *  @details  This event will:
         *              Fixe and unhidden the Monitor canvas
         *              Hidden Applications, Multimeida and Configurations canvas
         *            A pinned canvas will not be hidden until a short click on Configurations button
         *  @note     Do nothing if Applications or Multimedia canvas is pinned
         **/
        case configurations_canvas_fix_event: /* configuration button is pressed */
            if (streamDecoButtons::applications_canvas.pinned())
                break;
            if (streamDecoButtons::multimedia_canvas.pinned())
                break;
            streamDecoButtons::configurations_canvas.pin();
            streamDecoCanvas::applications.hidden();
            streamDecoCanvas::multimedia.hidden();
            streamDecoCanvas::configurations.hidden();
            streamDecoCanvas::monitor.unhidden();
            break;

            /* --- APPLICATIONS CANVAS --- */

        /** @brief    App1 button is pressed
         *  @details  GOG.com Icon to launch GOG Galaxy desktop application
         *  @note     Need configuration on application or system
         **/
        case applications_canvas_app1_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('9');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App2 button is pressed
         *  @details  Discord Icon to launch Discord desktop application
         *  @note     Need configuration on application or system
         **/
        case applications_canvas_app2_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('0');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App3 button is pressed
         *  @details  FPS Icon to show metrics
         *  @note     Need configuration on application or system
         **/
        case applications_canvas_app3_event:
#if 1
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('o');
#else
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('F');
#endif
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App4 button is pressed
         *  @details  VSCode Icon to launch VSCode desktop application
         *  @note     Need configuration on application or system
         **/
        case applications_canvas_app4_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('c');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App5 button is pressed
         *  @details  Tex Icon to launch LaTeX IDE desktop application
         *  @note     Need configuration on application or system
         **/
        case applications_canvas_app5_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('t');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App6 button is pressed
         *  @details  Calculator Icon to launch calculator desktop application
         *  @note     This shortcut may work by default on Windows and Linux
         **/
        case applications_canvas_app6_event:
            bleKeyboard.write(KEY_MEDIA_CALCULATOR);
            break;

        /** @brief    App7 button is pressed
         *  @details  In VScode build PlatformIO project
         *  @note     This shortcut may work by default on VSCode PlatformIO extension
         **/
        case applications_canvas_app7_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('b');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App8 button is pressed
         *  @details  In VScode upload PlatformIO project to microcontroler or SoC
         *  @note     This shortcut may work by default on VSCode PlatformIO extension
         **/
        case applications_canvas_app8_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('u');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    App9 button is pressed
         *  @details  In VScode open serial monitor on PlatformIO
         *  @note     This shortcut may work by default on VSCode PlatformIO extension
         **/
        case applications_canvas_app9_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('s');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /* --- MULTIMEDIA CANVAS --- */

        /** @brief    Mult1 button is pressed
         *  @details  Start or pause a record screen
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult1_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('r');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            streamDecoButtons::mult1.iconSwap();
            streamDecoButtons::mult1.pinned() ? streamDecoButtons::mult1.unpin() : streamDecoButtons::mult1.pin();
            break;

        /** @brief    Mult2 button is pressed
         *  @details  Mute mic on record
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult2_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('m');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            streamDecoButtons::mult2.iconSwap();
            streamDecoButtons::mult2.pinned() ? streamDecoButtons::mult2.unpin() : streamDecoButtons::mult2.pin();
            break;

        /** @brief    Mult3 button is pressed
         *  @details  Enable or disable webcam
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult3_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press(KEY_PRTSC);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult4 button is pressed
         *  @details  Add clip
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult4_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('r');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult5 button is pressed
         *  @details  Ripple track
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult5_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('t');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult6 button is pressed
         *  @details  Roll track
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult6_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('y');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult7 button is pressed
         *  @details  Backward track
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult7_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('t');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult8 button is pressed
         *  @details  Play/Pause track
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult8_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('1');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Mult9 button is pressed
         *  @details  Forward track
         *  @note     Need configuration on application or system
         **/
        case multimedia_canvas_mult9_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press('p');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /* --- CONFIGURATIONS CANVAS --- */

        /** @brief    Volmut button is pressed
         *  @details  Mute sound volume
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case configuration_canvas_volmut_event:
            bleKeyboard.write(KEY_MEDIA_MUTE);
            break;

        /** @brief    Voldown button is pressed
         *  @details  Lower the sound volume
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case configuration_canvas_voldown_event:
            bleKeyboard.write(KEY_MEDIA_VOLUME_DOWN);
            streamDecoTasks::buttons.takeNotify();
            break;

        /** @brief    Volup button is pressed
         *  @details  Rise sound volume
         *  @note     This media shortcut may work by default on Windows and Linux
         **/
        case configuration_canvas_volup_event:
            bleKeyboard.write(KEY_MEDIA_VOLUME_UP);
            streamDecoTasks::buttons.takeNotify();
            break;

        /** @brief    Colorbackground button is pressed
         *  @details  Change background color
         *  @note     Background colors are allocated in vector colors_background in streamDeco_settings.cpp file
         *            You can add colors in this vector
         **/
        case configuration_canvas_colorbackground_event:
            settings::cache.color_background = settings::nextBackgroundColor();
            lvgl::screen::set_bg_color(settings::cache.color_background);
            settings::flash = settings::cache;
            break;

        /** @brief    Colorbutton button is pressed
         *  @details  Change button color
         *  @note     Buttons colors are allocated in vector colors_button in streamDeco_settings.cpp file
         *            You can add colors in this vector
         **/
        case configuration_canvas_colorbutton_event:
            settings::cache.color_buttons = settings::nextButtonColor();
            streamDecoButtons::color(settings::cache.color_buttons);
            streamDecoBrightSlider::color(settings::cache.color_buttons);
            streamDecoMonitor::color(settings::cache.color_buttons);
            settings::flash = settings::cache;
            lvgl::screen::refresh();
            break;

        /** @brief    Rotate screen button is pressed
         *  @details  Rotate the streamDeco screen
         *  @note     Work in progress
         **/
        case configuration_canvas_rotate_screen_event:
            rotation = lvgl::screen::get_rotation();
            if (rotation == lvgl::screen::LANDSCAPE)
            {
                settings::cache.rotation = lvgl::screen::PORTRAIT;
                lvgl::screen::set_rotation(lvgl::screen::PORTRAIT);
                streamDecoCanvas::portrait();
                streamDecoBrightSlider::portrait();
                streamDecoButtons::portrait();
            }
            else
            {
                settings::cache.rotation = lvgl::screen::LANDSCAPE;
                lvgl::screen::set_rotation(lvgl::screen::LANDSCAPE);
                streamDecoCanvas::landscape();
                streamDecoBrightSlider::landscape();
                streamDecoButtons::landscape();
            }
            settings::flash = settings::cache;
            break;

        /** @brief    Sysmon button is pressed
         *  @details  Launch system monitor
         *  @note     This shortcut may work by default on Windows 10 or 11
         *            On Linux need configuration on system
         **/
        case configuration_canvas_sysmonitor_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_SHIFT);
            bleKeyboard.press(KEY_ESC);
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Sysconf button is pressed
         *  @details  Launch system configuration panel
         *  @note     This shortcut may work by default on Windows 10 or 11
         *            On Linux need configuration on system
         **/
        case configuration_canvas_sysconfig_event:
            bleKeyboard.press(KEY_LEFT_GUI);
            bleKeyboard.press('i');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Logout button is pressed
         *  @details  Logout of the computer
         *  @note     Need configuration on system or application
         **/
        case configuration_canvas_logout_event:
            break;

        /** @brief    Reboot button is pressed
         *  @details  Reboot the computer
         *  @note     Need configuration on system or application
         **/
        case configuration_canvas_reboot_event:
            esp::system::reset();
            break;

        /** @brief    Shuntdown button is pressed
         *  @details  Shuntdown the computer
         *  @note     Need configuration on system or application
         **/
        case configuration_canvas_shutdown_event:
            bleKeyboard.press(KEY_LEFT_CTRL);
            bleKeyboard.press(KEY_LEFT_ALT);
            bleKeyboard.press('k');
            rtos::sleep(10ms);
            bleKeyboard.releaseAll();
            break;

        /** @brief    Backlight bright control slider change value
         *  @details  Set new value to backlight bright
         **/
        case slider_backlight_bright_value_change_event:
            settings::cache.lcd_bright = streamDecoBrightSlider::read();
            settings::flash = settings::cache;
            break;

        } // end switch case

    } // end process event

} // namespace streamDeco